name: expense_log
description: "Expense Tracker Application"
publish_to: 'none' 

version: 3.2.4+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  permission_handler: ^12.0.1
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  file_picker: ^10.3.6
  path_provider: ^2.0.2
  http: ^1.2.0
  url_launcher: ^6.3.1
  package_info_plus: ^9.0.0 # 5.0.1
  lottie: ^3.3.2
  dio: ^5.0.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.5.2
  google_sign_in: ^6.1.0
  flutter_local_notifications: ^19.5.0 # 15.0.0
  timezone: ^0.10.1
  flutter_easyloading: ^3.0.0
  share_plus: ^12.0.1
  fl_chart: ^1.1.1
  image_picker: ^1.0.4
  pdf: ^3.11.1
  flutter_downloader: ^1.11.2
  open_file: ^3.2.1
  flutter_pdfview: ^1.3.2
  font_awesome_flutter: ^10.7.0
  flutter_speed_dial: ^7.0.0
  android_alarm_manager_plus: ^5.0.0
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  table_calendar: ^3.0.8
  flutter_markdown: ^0.7.7+1
  telephony: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.4
 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/terminal.png"

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
     - assets/add-note.json
     - assets/amongus.png
     - assets/icons/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-Italic.ttf
           style: italic
